In [7]:
# Question 1

import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

# (a) Add 2°C
updatedTemperature = temperature + 2
print("1(a):", updatedTemperature)

# (b) Celsius to Fahrenheit
fahrenheit = (9 / 5) * temperature + 32
print("1(b):", fahrenheit)

# (c) Readings greater than 32°C
greaterThan32 = temperature[temperature > 32]
print("1(c):", greaterThan32)

# (d) Count readings greater than 32°C
count = np.sum(temperature > 32)
print("1(d):", count)

# (e) Explanation
print("\n1(e):")
print("Vectorization performs operations on the entire array without loops")
print("Boolean indexing filters values directly using conditions")
print("Both methods are faster and more efficient than explicit iteration.")

1(a): [27 30 33 37 40 29 35 42]
1(b): [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
1(c): [35 38 33 40]
1(d): 4

1(e):
Vectorization performs operations on the entire array without loops
Boolean indexing filters values directly using conditions
Both methods are faster and more efficient than explicit iteration.


In [8]:
# Question 2

import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# (a)
totalSteps = np.sum(steps)
print("2(a):", totalSteps)

# (b)
meanSteps = np.mean(steps)
print("2(b):", meanSteps)

# (c)
print("2(c) Maximum:", np.max(steps))
print("2(c) Minimum:", np.min(steps))

# (d)
dayWiseTotal = np.sum(steps, axis=0)
print("2(d):", dayWiseTotal)

# (e)
userWiseTotal = np.sum(steps, axis=1)
print("2(e):", userWiseTotal)

# (f)
maxPosition = np.unravel_index(np.argmax(steps), steps.shape)
print("2(f):", maxPosition)

2(a): 84200
2(b): 7016.666666666667
2(c) Maximum: 9500
2(c) Minimum: 4500
2(d): [26500 27300 30400]
2(e): [18300 24500 14400 27000]
2(f): (np.int64(3), np.int64(2))


In [9]:
# Question 3

import numpy as np

# (a)
original = np.array([1, 2, 3, 4, 5, 6])
print("3(a):", original)

# (b)
subset = original[1:5]
print("3(b):", subset)

# (c)
subset[0] = 999
print("3(c) Original:", original)
print("3(c) Subset:", subset)

# (d)
copiedArray = original[1:5].copy()
copiedArray[0] = 500
print("3(d) Original:", original)
print("3(d) Copied:", copiedArray)

# (e)
matrix = np.arange(1, 13).reshape(3, 4)
print("3(e):")
print(matrix)

# (f)
print("3(f) First Row:", matrix[0])
print("3(f) Last Row:", matrix[-1])
print("3(f) Second Column:", matrix[:, 1])
print("3(f) Rows 1-2 & Cols 2-3:")
print(matrix[0:2, 1:3])

# (g)
flattenArray = matrix.flatten()
ravelArray = matrix.ravel()
print("3(g) Flatten:", flattenArray)
print("3(g) Ravel:", ravelArray)

# (h)
ravelArray[0] = 100
print("3(h) Matrix after ravel modification:")
print(matrix)

# Reset matrix
matrix = np.arange(1, 13).reshape(3, 4)

# (i)
flattenArray = matrix.flatten()
flattenArray[0] = 200
print("3(i) Matrix after flatten modification:")
print(matrix)

# (j)
print("3(j) Shape:", matrix.shape)
print("3(j) Dimensions:", matrix.ndim)
print("3(j) Size:", matrix.size)
print("3(j) Data Type:", matrix.dtype)

3(a): [1 2 3 4 5 6]
3(b): [2 3 4 5]
3(c) Original: [  1 999   3   4   5   6]
3(c) Subset: [999   3   4   5]
3(d) Original: [  1 999   3   4   5   6]
3(d) Copied: [500   3   4   5]
3(e):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3(f) First Row: [1 2 3 4]
3(f) Last Row: [ 9 10 11 12]
3(f) Second Column: [ 2  6 10]
3(f) Rows 1-2 & Cols 2-3:
[[2 3]
 [6 7]]
3(g) Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
3(g) Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
3(h) Matrix after ravel modification:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
3(i) Matrix after flatten modification:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3(j) Shape: (3, 4)
3(j) Dimensions: 2
3(j) Size: 12
3(j) Data Type: int64


In [10]:
# Question 4

import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

# (a)
print("4(a) Shape:", X.shape)
print("4(a) Dimensions:", X.ndim)

# (b)
transposeMatrix = X.T
print("\n4(b) Transpose:")
print(transposeMatrix)
print("Transpose converts rows into columns and columns into rows.")

# (c)
xtx = transposeMatrix @ X
print("\n4(c) X.T @ X:")
print(xtx)

# (d)
inverseMatrix = np.linalg.inv(xtx)
print("\n4(d) Inverse:")
print(inverseMatrix)

# (e)
beta = inverseMatrix @ transposeMatrix @ y
print("\n4(e) Coefficients:")
print(beta)

# (f)
print("\n4(f):")
print("Coefficient 1 -> Effect of sleep hours")
print("Coefficient 2 -> Effect of activity level")
print("Coefficient 3 -> Effect of stress level")
print("Each value shows the change in assistance score for one unit increase in that feature.")

# (g)
newUser = np.array([5, 40, 7])
predictedScore = newUser @ beta
print("\n4(g) Predicted Assistance Score:", predictedScore)

4(a) Shape: (4, 3)
4(a) Dimensions: 2

4(b) Transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
Transpose converts rows into columns and columns into rows.

4(c) X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

4(d) Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

4(e) Coefficients:
[-0.15921454  0.14083853 10.06302242]

4(f):
Coefficient 1 -> Effect of sleep hours
Coefficient 2 -> Effect of activity level
Coefficient 3 -> Effect of stress level
Each value shows the change in assistance score for one unit increase in that feature.

4(g) Predicted Assistance Score: 75.27862544779134
