In [21]:
# Question 1 (a)

import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

result_array = numbers + 2

print("Original Array :", numbers)
print("After Addition :", result_array)

Original Array : [10 20 30 40 50]
After Addition : [12 22 32 42 52]


In [12]:
# Question 1 (b)

import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

result_array = numbers * 3

print("Original Array :", numbers)
print("After Multiplication :", result_array)

Original Array : [10 20 30 40 50]
After Multiplication : [ 30  60  90 120 150]


In [13]:
# Question 1 (c)

import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

result_array = numbers / 2

print("Original Array :", numbers)
print("After Division :", result_array)

Original Array : [10 20 30 40 50]
After Division : [ 5. 10. 15. 20. 25.]


In [14]:
# Question 2 (a)

import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

reversed_array = arr[::-1]

print("Original Array :", arr)
print("Reversed Array :", reversed_array)

Original Array : [1 2 3 6 4 5]
Reversed Array : [5 4 6 3 2 1]


In [23]:
# Question 2 (b-i)

import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

most_frequent = np.bincount(x).argmax()
indices = np.where(x == most_frequent)[0]

print("Array :", x)
print("Most Frequent Value :", most_frequent)
print("Indices :", indices)

Array : [1 2 3 4 5 1 2 1 1 1]
Most Frequent Value : 1
Indices : [0 5 7 8 9]


In [16]:
# Question 2 (b-ii)

import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_frequent = np.bincount(y).argmax()
indices = np.where(y == most_frequent)[0]

print("Array :", y)
print("Most Frequent Value :", most_frequent)
print("Indices :", indices)

Array : [1 1 1 2 3 4 2 4 3 3]
Most Frequent Value : 1
Indices : [0 1 2]


In [22]:
# Question 3 (a)

import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

element = arr[0, 1]

print("Element :", element)

Element : 20


In [18]:
# Question 3 (b)

import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

element = arr[2, 0]

print("Element :", element)

Element : 70


In [19]:
# Question 4

import numpy as np

diya = np.linspace(10, 100, 25)

print("Array :")
print(diya)

print("\nDimensions :", diya.ndim)
print("Shape :", diya.shape)
print("Total Elements :", diya.size)
print("Data Type :", diya.dtype)
print("Total Bytes :", diya.nbytes)

transpose_array = diya.reshape(25, 1)

print("\nTranspose using reshape():")
print(transpose_array)

print("\nUsing T attribute:")
print(diya.T)

Array :
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions : 1
Shape : (25,)
Total Elements : 25
Data Type : float64
Total Bytes : 200

Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [24]:
# Question 5

import numpy as np

ucs420_diya = np.array([[10, 20, 30, 40],
                        [50, 60, 70, 80],
                        [90, 15, 20, 35]])

print("Original Array :")
print(ucs420_diya)

print("\nMean :", np.mean(ucs420_diya))
print("Median :", np.median(ucs420_diya))
print("Maximum :", np.max(ucs420_diya))
print("Minimum :", np.min(ucs420_diya))
print("Unique Elements :", np.unique(ucs420_diya))

reshaped_ucs420_diya = ucs420_diya.reshape(4, 3)

print("\nReshaped Array (4 x 3):")
print(reshaped_ucs420_diya)

resized_ucs420_diya = np.resize(ucs420_diya, (2, 3))

print("\nResized Array (2 x 3):")
print(resized_ucs420_diya)

Original Array :
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean : 43.333333333333336
Median : 37.5
Maximum : 90
Minimum : 10
Unique Elements : [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
