In [1]:
# Import NumPy

import numpy as np

print("NumPy imported successfully!")

NumPy imported successfully!


In [2]:
# Python List vs NumPy Array

# Python List
py_list = [10, 20, 30, 40]

# NumPy Array
np_array = np.array([10, 20, 30, 40])

print("Python List:", py_list)
print("NumPy Array:", np_array)

print("\nType of List:", type(py_list))
print("Type of NumPy Array:", type(np_array))

Python List: [10, 20, 30, 40]
NumPy Array: [10 20 30 40]

Type of List: <class 'list'>
Type of NumPy Array: <class 'numpy.ndarray'>


In [3]:
# 1D, 2D Arrays

# 1D Array
a1 = np.array([1, 2, 3, 4])

# 2D Array
a2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


print("1D Array:\n", a1)
print("\n2D Array:\n", a2)

1D Array:
 [1 2 3 4]

2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Array Attributes

a = np.array([10, 20, 30, 40, 50])

print("Array:", a)

print("dtype :", a.dtype)
print("size  :", a.size)
print("ndim  :", a.ndim)
print("shape :", a.shape)
print("nbytes:", a.nbytes)

Array: [10 20 30 40 50]
dtype : int64
size  : 5
ndim  : 1
shape : (5,)
nbytes: 40


In [5]:
# Indexing

arr = np.array([20, 1, 2, 3, 4])

print("Original Array:", arr)

print("\nFirst element:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])

Original Array: [20  1  2  3  4]

First element: 20
Third element: 2
Last element: 4


In [6]:
# Modifying Elements

arr = np.array([20, 1, 2, 3, 4])

print("Before:", arr)

arr[0] = 100
arr[4] = 0

print("After :", arr)

Before: [20  1  2  3  4]
After : [100   1   2   3   0]


In [7]:
# Slicing

arr = np.array([100, , 0])
1, 2, 3
print("Original:", arr)

print("arr[1:4] :", arr[1:4])
print("arr[:3]  :", arr[:3])
print("arr[2:]  :", arr[2:])
print("Reverse  :", arr[::-1])

Original: [100   1   2   3   0]
arr[1:4] : [1 2 3]
arr[:3]  : [100   1   2]
arr[2:]  : [2 3 0]
Reverse  : [  0   3   2   1 100]


In [8]:
# 2D Array Indexing

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr)

print("\n1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])
print("Entire 2nd row:", arr[1])
print("Entire 3rd column:", arr[:, 2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]

1st row, 2nd column: 20
3rd row, 1st column: 70
Entire 2nd row: [40 50 60]
Entire 3rd column: [30 60 90]


In [9]:
# Why NumPy is Better

# Python Loop

a = [1, 2, 3, 4]
b = [10, 20, 30, 40]

result = []

for i in range(len(a)):
    result.append(a[i] * b[i])

print(result)

[10, 40, 90, 160]


In [10]:
# NumPy Version

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

result = a * b

print(result)

[ 10  40  90 160]


In [11]:
# Vector Addition

u = np.array([1, 0])
v = np.array([0, 1])

z = u + v

print("u =", u)
print("v =", v)
print("z =", z)

u = [1 0]
v = [0 1]
z = [1 1]


In [12]:
# Vector Subtraction

u = np.array([1, 0])
v = np.array([0, 1])

z = u - v

print(z)

[ 1 -1]


In [13]:
# Scalar Multiplication

y = np.array([1, 2])

print("Original:", y)

print("Multiply by 2:", 2 * y)
print("Multiply by 5:", 5 * y)

Original: [1 2]
Multiply by 2: [2 4]
Multiply by 5: [ 5 10]


In [14]:
# Basic Arithmetic on Arrays

arr = np.array([10, 20, 30, 40])

print("Original:", arr)

print("Add 2      :", arr + 2)
print("Subtract 5 :", arr - 5)
print("Multiply 3 :", arr * 3)
print("Divide by 2:", arr / 2)

Original: [10 20 30 40]
Add 2      : [12 22 32 42]
Subtract 5 : [ 5 15 25 35]
Multiply 3 : [ 30  60  90 120]
Divide by 2: [ 5. 10. 15. 20.]
